Update Arrow to v1.2.3
AnacondaRecipes/arrow-feedstock pull request #6
Opened 2022-10-24 20:08 UTC by ELundby45

# Update Arrow to v1.2.3

- Update version and SHA256
- Revert noarch build
- Update pinnings for  `pytz >=2021.1` and `implejson >=3.*` to match [upstream](https://github.com/arrow-py/arrow/blob/1.2.3/requirements/requirements-tests.txt)
- Add missing `license_url`

2022-10-24 20:35 UTC, cbouss requested changes

2022-10-24 20:35 UTC, cbouss commented on recipe/meta.yaml
>      - typing_extensions
You could restrict typing_extensions to py < 3.8
https://github.com/arrow-py/arrow/blob/1.2.3/setup.py#L27
`typing_extensions #[py<38]`

2022-10-24 20:35 UTC, cbouss commented on recipe/meta.yaml
>      # 2022/4/5: tests on s390x fail because dateparser requires tzlocal bit it's currently not available on s390x
tzlocal was added recently to s390x (see [anaconda.org](https://anaconda.org/main/tzlocal/files?version=1.5.1))
I think this comment can be removed, as well as the test restriction.
--> `cd tests && pytest --cov arrow`

2022-10-24 21:50 UTC, cbouss approved these changes
LGTM!

2022-10-25 11:58 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True  #[py<36]
missing whitespace `# [py<36]` (it's for readability)

2022-10-25 11:58 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - typing_extensions  #[py<38]
missing whitespace `# [py<38]`

2022-10-25 11:58 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: https://github.com/crsmithdev/arrow
`home` and dev urls should be `https://github.com/arrow-py/arrow`

2022-10-25 11:58 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: https://github.com/crsmithdev/arrow
`doc_source_url` is `https://github.com/arrow-py/arrow/tree/master/docs`

2022-10-25 14:38 UTC, skupr-anaconda approved these changes

2022-10-25 19:38 UTC, varlackc approved these changes
LGTM

2022-10-25 19:40 UTC, merged